// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3aX3uqQ4D5XR29e9iiQoBPrbA3xEQHpU',
    appId: '1:997133946428:web:2bcdc158a61750bd7b7d39',
    messagingSenderId: '997133946428',
    projectId: 'dtapps-f3442',
    authDomain: 'dtapps-f3442.firebaseapp.com',
    storageBucket: 'dtapps-f3442.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyB4dKIcrl1j72VmAeO-FWDu8xZZwmjZjns",
      authDomain: "bookapp-5ad59.firebaseapp.com",
      projectId: "bookapp-5ad59",
      storageBucket: "bookapp-5ad59.firebasestorage.app",
      messagingSenderId: "481049957521",
      appId: "1:481049957521:web:35229496af9c4d8ed55b30",
      measurementId: "G-FH4R0W29M3"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZIG5jliiUTC4KkaBAPFx4W2TEFZ9DCw',
    appId: '1:997133946428:ios:636a9dfc4779dbdd7b7d39',
    messagingSenderId: '997133946428',
    projectId: 'dtapps-f3442',
    storageBucket: 'dtapps-f3442.appspot.com',
    androidClientId:
        '997133946428-1bjhhs7ffu0ur543qokrm4oesjansibu.apps.googleusercontent.com',
    //iosClientId:
        //'997133946428-s8u6qgp7jjvjlokjr5jf8uu981qlevem.apps.googleusercontent.com',
   // iosBundleId: 'com.divinetechs.dtpocketfm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeZIG5jliiUTC4KkaBAPFx4W2TEFZ9DCw',
    appId: '1:997133946428:ios:636a9dfc4779dbdd7b7d39',
    messagingSenderId: '997133946428',
    projectId: 'dtapps-f3442',
    storageBucket: 'dtapps-f3442.appspot.com',
    androidClientId:
        '997133946428-1bjhhs7ffu0ur543qokrm4oesjansibu.apps.googleusercontent.com',
    iosClientId:
        '997133946428-s8u6qgp7jjvjlokjr5jf8uu981qlevem.apps.googleusercontent.com',
    //iosBundleId: 'com.divinetechs.dtpocketfm',
  );
}
